# python base
FROM mrcschwering/python-base-numpy:latest

LABEL purpose="python with some basic libraries including numpy and pandas"
LABEL maintainer="schweringmarc01@gmail.com"

# cause slow
RUN pip3 install pandas
